# Generated by Django 3.2.9 on 2021-11-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='Type a dojo description!'),
        ),
    ]
