# Generated by Django 3.2.9 on 2021-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20211129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='comments',
            field=models.TextField(default='Type the Course Comments Here'),
        ),
    ]
